### ISSUE TITLE
Another error

### ISSUE THREAD

**Issue by elieobeid7** [lavender/lavender#13] opened 2015-04-06 09:37 UTC
[Symfony\Component\Debug\Exception\FatalErrorException]                     
  Class App\Database\Store contains 1 abstract method and must therefore be   
  declared abstract or implement the remaining methods (Lavender\Contracts\E  
  ntity\Model::setUnguardState)

**Comment by ryaan-anthony** [comment] 2015-04-06 15:22
duplicate of #12 
will push fix with planned tagged release this afternoon. thanks for the feedback!

**Closed by ryaan-anthony** 2015-04-06 15:22 UTC
